-- MySQL Script generated by MySQL Workbench
-- Qua 01 Jun 2016 11:55:05 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBagendamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBagendamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBagendamento` DEFAULT CHARACTER SET utf8 ;
USE `DBagendamento` ;

-- -----------------------------------------------------
-- Table `DBagendamento`.`FILIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`FILIAL` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`PROFISSAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`PROFISSAO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`FUNCIONARIO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `profissao_codigo` INT NOT NULL,
  `nome` VARCHAR(30) NULL,
  `endereco` VARCHAR(25) NULL,
  `FILIAL_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_FUNCIONARIO_profissao_idx` (`profissao_codigo` ASC),
  INDEX `fk_FUNCIONARIO_FILIAL1_idx` (`FILIAL_codigo` ASC),
  CONSTRAINT `fk_FUNCIONARIO_profissao`
    FOREIGN KEY (`profissao_codigo`)
    REFERENCES `DBagendamento`.`PROFISSAO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_FILIAL1`
    FOREIGN KEY (`FILIAL_codigo`)
    REFERENCES `DBagendamento`.`FILIAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`CLIENTE` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`STATUS` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`VEICULO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(7) NULL,
  `marca` VARCHAR(20) NULL,
  `modelo` VARCHAR(20) NULL,
  `STATUS_codigo` INT NOT NULL,
  `FILIAL_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `STATUS_codigo`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `fk_VEICULO_STATUS1_idx` (`STATUS_codigo` ASC),
  INDEX `fk_VEICULO_FILIAL1_idx` (`FILIAL_codigo` ASC),
  CONSTRAINT `fk_VEICULO_STATUS1`
    FOREIGN KEY (`STATUS_codigo`)
    REFERENCES `DBagendamento`.`STATUS` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_FILIAL1`
    FOREIGN KEY (`FILIAL_codigo`)
    REFERENCES `DBagendamento`.`FILIAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBagendamento`.`AGENDAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBagendamento`.`AGENDAMENTO` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `horariosaida` DATETIME NOT NULL,
  `horarioretorno` DATETIME NOT NULL,
  `VEICULO_codigo` INT NOT NULL,
  `FUNCIONARIO_codigo` INT NOT NULL,
  `FILIAL_codigo` INT NOT NULL,
  `CLIENTE_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_AGENDAMENTO_VEICULO1_idx` (`VEICULO_codigo` ASC),
  INDEX `fk_AGENDAMENTO_FUNCIONARIO1_idx` (`FUNCIONARIO_codigo` ASC),
  INDEX `fk_AGENDAMENTO_FILIAL1_idx` (`FILIAL_codigo` ASC),
  INDEX `fk_AGENDAMENTO_CLIENTE1_idx` (`CLIENTE_codigo` ASC),
  CONSTRAINT `fk_AGENDAMENTO_VEICULO1`
    FOREIGN KEY (`VEICULO_codigo`)
    REFERENCES `DBagendamento`.`VEICULO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTO_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_codigo`)
    REFERENCES `DBagendamento`.`FUNCIONARIO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTO_FILIAL1`
    FOREIGN KEY (`FILIAL_codigo`)
    REFERENCES `DBagendamento`.`FILIAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDAMENTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo`)
    REFERENCES `DBagendamento`.`CLIENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
