/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Agendamento.AgendamentoLocacao;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.Date;

/**
 *
 * @author michael.aroriz
 */
public class MenuAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form MenuAgendamento
     */
    public MenuAgendamento() {
        initComponents();
        jLabelMsgCidade.setVisible(false);
        jLabelMsgDataDev.setVisible(false);
        jLabelMsgDataRet.setVisible(false);
        jLabelMsgLocal.setVisible(false);
        jLabelMsgPais.setVisible(false);
        jLabelMsgSelectIdade.setVisible(false);
        jLabelMsgDateValido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textPais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textLocal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textHoraRet = new javax.swing.JComboBox();
        textMinRet = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textHoraDev = new javax.swing.JComboBox();
        textMinDev = new javax.swing.JComboBox();
        checkBoxIdade = new javax.swing.JCheckBox();
        ButtonCancelar = new javax.swing.JButton();
        ButtonConcluir = new javax.swing.JButton();
        jLabelMsgPais = new javax.swing.JLabel();
        jLabelMsgCidade = new javax.swing.JLabel();
        jLabelMsgLocal = new javax.swing.JLabel();
        jLabelMsgDataRet = new javax.swing.JLabel();
        jLabelMsgDataDev = new javax.swing.JLabel();
        jLabelMsgSelectIdade = new javax.swing.JLabel();
        jLabelMsgDateValido = new javax.swing.JLabel();
        jDateRetirada = new com.toedter.calendar.JDateChooser();
        jDateDevolucao = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Agendamento");
        jInternalFrame1.setVisible(true);

        jPanel1.setName("\n"); // NOI18N

        jLabel1.setText("País:");

        jLabel2.setText("Cidade:");

        textCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCidadeActionPerformed(evt);
            }
        });

        jLabel3.setText("Local:");

        jLabel4.setText("*devolver veículo no mesmo local");

        jLabel5.setText("Data de retirada:");

        jLabel6.setText("Hora:");

        textHoraRet.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"00", "01", "02", "03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"}));
        textHoraRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHoraRetActionPerformed(evt);
            }
        });

        textMinRet.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"00", "30" }));
        textMinRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinRetActionPerformed(evt);
            }
        });

        jLabel7.setText("Data de Devolução:");

        jLabel8.setText("Hora:");

        textHoraDev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23" }));

        textMinDev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "30" }));

        checkBoxIdade.setText("Condutor acima de 18 anos");
        checkBoxIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIdadeActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonConcluir.setText("Concluir");
        ButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConcluirActionPerformed(evt);
            }
        });

        jLabelMsgPais.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgPais.setText("*Campo obrigatório");

        jLabelMsgCidade.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgCidade.setText("*Campo obrigatório");

        jLabelMsgLocal.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgLocal.setText("*Campo obrigatório");

        jLabelMsgDataRet.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgDataRet.setText("*Campo obrigatório");

        jLabelMsgDataDev.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgDataDev.setText("*Campo obrigatório");

        jLabelMsgSelectIdade.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMsgSelectIdade.setText("*Campo obrigatório");

        jLabelMsgDateValido.setText("*Data de devolução deve ser maior que data de retirada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textLocal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jDateRetirada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(textHoraRet, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textMinRet, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(91, 91, 91)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textHoraDev, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMinDev, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPais))
                    .addComponent(jLabelMsgPais)
                    .addComponent(jLabelMsgCidade)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMsgLocal)
                    .addComponent(jLabel4)
                    .addComponent(jLabelMsgDataRet)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMsgDataDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMsgDateValido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonConcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelMsgSelectIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkBoxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMsgPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMsgCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabelMsgLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textHoraRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textMinRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMsgDataRet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textHoraDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textMinDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMsgDataDev)
                    .addComponent(jLabelMsgDateValido))
                .addGap(18, 18, 18)
                .addComponent(checkBoxIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMsgSelectIdade)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonConcluir)))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("ggg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static AgendamentoLocacao mag = new AgendamentoLocacao(null, null, null, null, null, null, null);
    
    private void checkBoxIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIdadeActionPerformed

    private void textCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCidadeActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConcluirActionPerformed
        
        //Variável necessária para verificação de campos preenchidos
        int j=0;
        if (ButtonConcluir.isEnabled()) {
            //Condição para identificar campos não preenchidos
            if (textPais.getText().isEmpty()) {
                jLabelMsgPais.setVisible(true);
            } else {
                jLabelMsgPais.setVisible(false);
                j++;
            }
            if (textCidade.getText().isEmpty()) {
                jLabelMsgCidade.setVisible(true);
            } else {
                jLabelMsgCidade.setVisible(false);
                j++;
            }
            if (textLocal.getText().isEmpty()) {
                jLabelMsgLocal.setVisible(true);
            } else {
                jLabelMsgLocal.setVisible(false);
                j++;
            }
            if (jDateRetirada.getJCalendar().isValid()) {
                jLabelMsgDataRet.setVisible(false);                
            } else {
                jLabelMsgDataRet.setVisible(true); 
                j++;
            }
            if (jDateDevolucao.getJCalendar().isValid()) {
                jLabelMsgDataDev.setVisible(false);                
            } else {
                jLabelMsgDataDev.setVisible(true);
                j++;
            }
            if (checkBoxIdade.isSelected()) {
                jLabelMsgSelectIdade.setVisible(false);
                j++;
            } else {
                jLabelMsgSelectIdade.setVisible(true);               
            }
            //Comparar duas datas
            Calendar calRet=jDateRetirada.getCalendar();
            Calendar calDev=jDateDevolucao.getCalendar();
            
            if(calRet.compareTo(calDev)==0||calRet.compareTo(calDev)==1){
                jLabelMsgDateValido.setVisible(true);
            }else if(calRet.compareTo(calDev)==-1){
                jLabelMsgDateValido.setVisible(false);           
                j++;
            }
        }        
        //Se todos os campos estiverem preenchidos, os dados são armazenados
        if (ButtonConcluir.isEnabled() && j == 7) { 
            mag.setCidade(textCidade.getText());
            mag.setLocal(textLocal.getText());
            mag.setPais(textPais.getText());
            mag.setDataretorno(jDateDevolucao.getDate());
            mag.setDatasaida(jDateRetirada.getDate());            
            
            mag.imprimi();
            
            //Concatenar duas strings para Int
            String horadev=textHoraDev.toString();
            String mindev=textMinDev.toString();
            String horariodev = horadev + "" + mindev;
           
            String horaret=textHoraDev.toString();
            String minret=textMinDev.toString();
            String horarioret = horaret + "" + minret;
            
            
            
            
            //fecha a janela de Cadastro e volta para o menu principal    
            this.dispose();
            new MenuPrincipal().setVisible(true);
        }        
        
             
        
    }//GEN-LAST:event_ButtonConcluirActionPerformed

    private void textHoraRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHoraRetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHoraRetActionPerformed

    private void textMinRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMinRetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMinRetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonConcluir;
    private javax.swing.JCheckBox checkBoxIdade;
    private com.toedter.calendar.JDateChooser jDateDevolucao;
    private com.toedter.calendar.JDateChooser jDateRetirada;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMsgCidade;
    private javax.swing.JLabel jLabelMsgDataDev;
    private javax.swing.JLabel jLabelMsgDataRet;
    private javax.swing.JLabel jLabelMsgDateValido;
    private javax.swing.JLabel jLabelMsgLocal;
    private javax.swing.JLabel jLabelMsgPais;
    private javax.swing.JLabel jLabelMsgSelectIdade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textCidade;
    private javax.swing.JComboBox textHoraDev;
    private javax.swing.JComboBox textHoraRet;
    private javax.swing.JTextField textLocal;
    private javax.swing.JComboBox textMinDev;
    private javax.swing.JComboBox textMinRet;
    private javax.swing.JTextField textPais;
    // End of variables declaration//GEN-END:variables
}
